{"name": "test_case01[5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 7 == 5\n  -7\n  +5", "trace": "self = <test_login.TestCase object at 0x000001522E794910>\nresult_data = 5, start = None\n\n    @pytest.mark.parametrize('result_data', result_list)\n    def test_case01(self, result_data, start):\n        result = add(3, 4)\n>       assert result == result_data  # 断言失败\nE       assert 7 == 5\nE         -7\nE         +5\n\nscripts\\test_login.py:25: AssertionError"}, "parameters": [{"name": "result_data", "value": "5"}], "start": 1592990967293, "stop": 1592990967293, "uuid": "3f7d53c6-2b8f-4645-870d-2b110d0623d0", "historyId": "3b4a842bdaa28739b1580c8b5587410e", "testCaseId": "fe37f97896f62867fcc8dab9c3f9e348", "fullName": "scripts.test_login.TestCase#test_case01", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "LAPTOP-7ES49RD3"}, {"name": "thread", "value": "3264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}