{"name": "test_login[15807012589-IV8Zy2bc99]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'", "trace": "self = <test_tpshop.TestTPshop object at 0x000001D1DD9B60A0>\nusername = '15807012589', password = 'IV8Zy2bc99'\n\n    @pytest.mark.parametrize('username, password', fake_data(10))\n    def test_login(self, username, password):\n>       write_yml_to_file([username, password], 'generate')\n\nscripts\\test_tpshop.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npy_object = ['15807012589', 'IV8Zy2bc99'], yaml_file = 'generate'\n\n    def write_yml_to_file(py_object, yaml_file):\n        from ruamel import yaml\n>       with open('../data/'+yaml_file+'.yml', 'a', encoding='utf-8')as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'\n\nbase\\base_yml.py:15: FileNotFoundError"}, "parameters": [{"name": "username", "value": "'15807012589'"}, {"name": "password", "value": "'IV8Zy2bc99'"}], "start": 1594453250750, "stop": 1594453250750, "uuid": "cc121098-1755-4782-950e-7c07b4ef8487", "historyId": "356fde95e8461668ff5569b9f2bad914", "testCaseId": "8ce2edbb4d3f11acca29596f7aaac53c", "fullName": "scripts.test_tpshop.TestTPshop#test_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_tpshop"}, {"name": "subSuite", "value": "TestTPshop"}, {"name": "host", "value": "LAPTOP-7ES49RD3"}, {"name": "thread", "value": "16148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_tpshop"}]}