{"name": "test_login[18550387780-ARybBnF80U]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'", "trace": "self = <test_tpshop.TestTPshop object at 0x000001D1DD79C370>\nusername = '18550387780', password = 'ARybBnF80U'\n\n    @pytest.mark.parametrize('username, password', fake_data(10))\n    def test_login(self, username, password):\n>       write_yml_to_file([username, password], 'generate')\n\nscripts\\test_tpshop.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npy_object = ['18550387780', 'ARybBnF80U'], yaml_file = 'generate'\n\n    def write_yml_to_file(py_object, yaml_file):\n        from ruamel import yaml\n>       with open('../data/'+yaml_file+'.yml', 'a', encoding='utf-8')as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'\n\nbase\\base_yml.py:15: FileNotFoundError"}, "parameters": [{"name": "username", "value": "'18550387780'"}, {"name": "password", "value": "'ARybBnF80U'"}], "start": 1594453250186, "stop": 1594453250445, "uuid": "86c67861-d2b7-4704-be35-440176056153", "historyId": "a012b504e06a1f6cdf6c866955095414", "testCaseId": "8ce2edbb4d3f11acca29596f7aaac53c", "fullName": "scripts.test_tpshop.TestTPshop#test_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_tpshop"}, {"name": "subSuite", "value": "TestTPshop"}, {"name": "host", "value": "LAPTOP-7ES49RD3"}, {"name": "thread", "value": "16148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_tpshop"}]}