{"uuid": "f8380a3b-2ba5-49ff-a606-c3f6287e80c6", "children": ["e1109afe-3ed9-4151-8554-1019f0b58f16"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestNetwork' has no attribute 'driver'\n", "trace": "  File \"e:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 722, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 660, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\数据分析\\scripts\\test_login.py\", line 12, in setup_class\n    self.driver = TestCalculate.nextone(self)\n  File \"E:\\数据分析\\scripts\\test_cal.py\", line 50, in nextone\n    self.driver.start_activity('com.android.settings', '.MiuiSettings')\n"}, "start": 1593073480995, "stop": 1593073480995}], "start": 1593073480995, "stop": 1593073481013}