{"name": "test_login[15540959024-2kp9CmRyRL]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'", "trace": "self = <test_tpshop.TestTPshop object at 0x000001D1DD9148E0>\nusername = '15540959024', password = '2kp9CmRyRL'\n\n    @pytest.mark.parametrize('username, password', fake_data(10))\n    def test_login(self, username, password):\n>       write_yml_to_file([username, password], 'generate')\n\nscripts\\test_tpshop.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npy_object = ['15540959024', '2kp9CmRyRL'], yaml_file = 'generate'\n\n    def write_yml_to_file(py_object, yaml_file):\n        from ruamel import yaml\n>       with open('../data/'+yaml_file+'.yml', 'a', encoding='utf-8')as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'\n\nbase\\base_yml.py:15: FileNotFoundError"}, "parameters": [{"name": "username", "value": "'15540959024'"}, {"name": "password", "value": "'2kp9CmRyRL'"}], "start": 1594453250615, "stop": 1594453250615, "uuid": "4989da29-54f6-4ecf-82b8-0688a95024a6", "historyId": "ef667fa0685717ebea70b4703d033cd5", "testCaseId": "8ce2edbb4d3f11acca29596f7aaac53c", "fullName": "scripts.test_tpshop.TestTPshop#test_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_tpshop"}, {"name": "subSuite", "value": "TestTPshop"}, {"name": "host", "value": "LAPTOP-7ES49RD3"}, {"name": "thread", "value": "16148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_tpshop"}]}